[package]
name = "prip"
version = "0.1.0"
edition = "2024"
description = "photo ripper"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.41", features = ["derive"] }
clap-verbosity-flag = "3.0.3"
env_logger = "0.11.8"
indicatif = "0.18.0"
log = "0.4.27"
